[package]
name = "fnd"
version = "0.1.0"
authors = ["Joshua Clayton <joshua.clayton@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
ignore = "0.4"
mimalloc = { version = "*", default-features = false }
regex = "1"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.dev]
split-debuginfo = "unpacked"
